### ISSUE TITLE
[BUG REPORT] Image file format selection only works with Chrome

### ISSUE THREAD

**Issue by chdietrich** [aarpon/hrm#5]
**Describe the bug**
The dropdown "Please choose file format..." (Launch jobs) resets after selection if you use the Mozilla Firefox web browser, Google Chrome works.

**To Reproduce**
HRM: Launch jobs -> Choose a file format

**Expected behavior**
After selecting the file type, it should remain selected.
With Chrome: https://youtu.be/1EYHoNYWXJQ

**Screenshots**
With Firefox: https://youtu.be/zFhTUlgthdc

**Environment**
***Server-side***
CentOS Linux release 7.6.1810
PHP 7.2.10
Apache/2.4.6
PostgreSQL 9.2.24
HRM 3.6.0

***Client-side***
Firefox 66.0.3 / Chrome 74.0.3729.108

**Comment by carstendietrich** [comment]
Hello,

the problem is a race condition, when you update the dropdown, an AJAX call is triggered in the background to save the settings in the user session. Because the page is also refreshed when the dropdown is changed, the behavior described above may occur if the page is updated before the AJAX call is evaluated.

**Comment by aarpon** [comment]
Thanks! Will test and merge asap.
